export { default as FacebookIcon } from "./FacebookIcon";
export { default as InstagramIcon } from "./InstagramIcon";
export { default as TwitterIcon } from "./TwitterIcon";
export { default as LinkedInIcon } from "./LinkedInIcon";
export { default as EmailIcon } from "./EmailIcon";
export { default as PhoneIcon } from "./PhoneIcon";
export { default as MenuIcon } from "./MenuIcon";
export { default as CloseIcon } from "./CloseIcon";
export { default as ServicesIcon } from "./ServicesIcon";
